# Generated by Django 4.0.6 on 2022-07-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=3)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.portfolio')),
            ],
        ),
    ]
